# Generated by Django 5.2.3 on 2025-07-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
